### ISSUE TITLE
Datadog agent setup failed

### ISSUE THREAD

**Issue by galunik** [DataDog/datadog-agent-orb#9]
## Orb version:

orbs:
  datadog-agent: datadog/agent@0

## What happened:

- datadog-agent/setup -  failed
![image](https://user-images.githubusercontent.com/25548298/147230561-1d910ee9-0347-42b8-bd9b-d541c9b32580.png)

## Expected behavior:

datadog-agent should be started successfully

## Additional Information:

Fail happened on 21 and 22 Dec 2021.

I am using datadog-agent as suggested in 
https://circleci.com/developer/orbs/orb/datadog/agent

```
version: 2.1

orbs:
  datadog-agent: datadog/agent@0


steps:
  - datadog-agent/setup
  - run:
          name: Running tests
          command: |
          run tests
 - datadog-agent/stop         
          
```
